builds:
  - main: ./cmd/tinylb
    binary: tinylb
archives:
  - format: gz
    files:
      - none*
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"